import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  container: {
    height: "100%",
    overflow: "hidden",
  },
  conversationPanel: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    paddingRight: "var(--space-4)",
  },
  workflowPanel: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    paddingLeft: "var(--space-4)",
    borderLeft: "1px solid var(--border)",
  },
  workflowPanelHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "var(--space-3)",
  },
  workflowPanelTitle: {
    fontSize: "var(--text-base)",
    fontWeight: 600,
    margin: 0,
  },
  workflowPanelEmpty: {
    color: "var(--text-muted)",
    fontSize: "var(--text-sm)",
  },
  workflowPanelList: {
    flex: 1,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-2)",
  },
  workflowPanelEvent: {
    display: "flex",
    gap: "var(--space-2)",
    fontSize: "var(--text-sm)",
    padding: "var(--space-1) 0",
    borderBottom: "1px solid var(--border-subtle)",
  },
  workflowPanelEventTime: {
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono)",
    fontSize: "var(--text-xs)",
    flexShrink: 0,
  },
  workflowPanelEventLabel: {
    color: "var(--text-secondary)",
  },

  // ConversationSwitcher
  switcher: { marginBottom: "var(--space-4)" },
  switcherBar: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-3)",
    fontSize: "var(--text-sm)",
  },
  switcherLabel: { color: "var(--text-secondary)", marginRight: "auto" },
  switcherButton: {
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-sm)",
    color: "var(--text-primary)",
    padding: "var(--space-1) var(--space-3)",
    fontSize: "var(--text-xs)",
    cursor: "pointer",
  },
  switcherList: {
    marginTop: "var(--space-2)",
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-1)",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-md)",
    padding: "var(--space-2)",
    maxHeight: "220px",
    overflowY: "auto",
    background: "var(--bg-surface)",
  },
  switcherHint: { color: "var(--text-muted)", fontSize: "var(--text-sm)", padding: "var(--space-1)" },
  switcherItem: {
    textAlign: "left",
    background: "transparent",
    border: "none",
    borderRadius: "var(--radius-sm)",
    color: "var(--text-secondary)",
    padding: "var(--space-2)",
    cursor: "pointer",
    fontSize: "var(--text-sm)",
  },
  switcherItemActive: {
    textAlign: "left",
    background: "var(--accent-bg)",
    border: "none",
    borderRadius: "var(--radius-sm)",
    color: "var(--text-primary)",
    padding: "var(--space-2)",
    cursor: "pointer",
    fontSize: "var(--text-sm)",
    fontWeight: 600,
  },

  // MessageList / Message — compact rows, not chat-bubbles.
  messageList: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-3)",
    overflowY: "auto",
    padding: "var(--space-2) 0",
  },
  messageListEmpty: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  messageListEmptyText: {
    color: "var(--text-muted)",
    fontSize: "var(--text-sm)",
  },
  message: {
    borderRadius: "var(--radius-md)",
    padding: "var(--space-2) var(--space-3)",
    maxWidth: "85%",
  },
  messageUser: {
    alignSelf: "flex-end",
    background: "var(--accent-bg)",
    border: "1px solid var(--accent-border)",
  },
  messageAgent: {
    alignSelf: "flex-start",
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
  },
  messageMeta: {
    display: "flex",
    alignItems: "baseline",
    gap: "var(--space-2)",
    marginBottom: "var(--space-1)",
  },
  messageRoleUser: {
    fontSize: "var(--text-xs)",
    fontWeight: 600,
    color: "var(--accent)",
  },
  messageRoleAgent: {
    fontSize: "var(--text-xs)",
    fontWeight: 600,
    color: "var(--text-secondary)",
  },
  messageTime: {
    fontSize: "var(--text-xs)",
    color: "var(--text-muted)",
  },
  messageContent: {
    margin: 0,
    fontSize: "var(--text-base)",
    color: "var(--text-primary)",
    whiteSpace: "pre-wrap",
    lineHeight: 1.5,
  },
  messageTyping: {
    margin: 0,
    fontSize: "var(--text-base)",
    color: "var(--text-muted)",
    fontStyle: "italic",
  },

  // MessageComposer
  composer: {
    display: "flex",
    gap: "var(--space-2)",
    borderTop: "1px solid var(--border)",
    paddingTop: "var(--space-3)",
    marginTop: "var(--space-3)",
  },
  composerInput: {
    flex: 1,
    padding: "var(--space-2) var(--space-3)",
    borderRadius: "var(--radius-md)",
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-sans)",
    fontSize: "var(--text-base)",
    resize: "none",
    maxHeight: "160px",
  },
  composerButton: {
    background: "var(--accent)",
    color: "var(--text-on-accent)",
    border: "none",
    borderRadius: "var(--radius-md)",
    padding: "0 var(--space-4)",
    fontSize: "var(--text-sm)",
    fontWeight: 600,
    cursor: "pointer",
  },
};
