import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  root: {
    width: 232,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    background: "var(--bg-surface)",
    borderRight: "1px solid var(--border)",
    height: "100vh",
    position: "sticky",
    top: 0,
    transition: "width 150ms ease",
  },
  rootCollapsed: {
    width: 60,
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-3)",
    padding: "var(--space-4)",
    borderBottom: "1px solid var(--border-subtle)",
    overflow: "hidden",
  },
  brandMark: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    height: 28,
    borderRadius: "var(--radius-md)",
    background: "var(--accent)",
    color: "var(--text-on-accent)",
    fontSize: "var(--text-xs)",
    fontWeight: 700,
    flexShrink: 0,
  },
  brandText: {
    fontSize: "var(--text-sm)",
    fontWeight: 600,
    color: "var(--text-primary)",
    whiteSpace: "nowrap",
  },
  nav: {
    flex: 1,
    overflowY: "auto",
    padding: "var(--space-3)",
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-4)",
  },
  group: { display: "flex", flexDirection: "column", gap: "var(--space-1)" },
  groupLabel: {
    fontSize: "var(--text-xs)",
    fontWeight: 600,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    padding: "0 var(--space-2)",
    marginBottom: "var(--space-1)",
  },
  link: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-3)",
    padding: "var(--space-2) var(--space-2)",
    borderRadius: "var(--radius-sm)",
    color: "var(--text-secondary)",
    textDecoration: "none",
    fontSize: "var(--text-sm)",
    whiteSpace: "nowrap",
  },
  linkCollapsed: {
    justifyContent: "center",
    padding: "var(--space-2)",
  },
  linkActive: {
    background: "var(--accent-bg)",
    color: "var(--text-primary)",
  },
  linkIcon: { flexShrink: 0 },
  collapseButton: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
    margin: "var(--space-3)",
    padding: "var(--space-2)",
    background: "transparent",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-sm)",
    color: "var(--text-muted)",
    fontSize: "var(--text-xs)",
    cursor: "pointer",
    justifyContent: "center",
  },
};
